---
title: "UVA StatLab Statistical Notes"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

###  Reports generated for various consultations for the UVA StatLab.

- [Extracting data from UpSet Plot](extract_data_upset_plot.html) (Clay Ford, 2025-04-10)     
How to extract specific interactions from a data frame identified in an UpSet plot.

- [Demo of Tukey HSD](tukey_hsd_demo.html) (Clay Ford, 2025-04-02)    
Quick demo of how Tukey HSD corrects p-values for multiple comparisons.

- [Understanding the log link in a Poisson model](glm_families_and_links.html) (Clay Ford, 2025-03-21)    
Why we use the log link with Poisson models (i.e., `family = poisson(link = "log")`).

- [Investigating Multicolinearity](investigating_multicollinearity.html) (Clay Ford, 2025-03-19)   
Investigating multicolinearity and challenging idea of inspecting pairwise correlations before fitting a model and dropping highly correlated predictors.

- [analyze correlational data with treatments](Correlational_Analysis_in_R.html) (Clay Ford, 2025-02-03)     
Assessing correlation between multiple sets of variables stratified by a treatment variable. Uses the `r.test()` function from the {psych} package.


- [Repeated Measures ANOVA examples](Correlational_Analysis_in_R.html) (Clay Ford, 2025-01-29)     
Two examples of repeated measures ANOVA: (1) Using raw follow-up data as the outcome with baseline as a covariate, and (2) Using change scores as the outcome. I prefer the first method. 


- [Comparing self-starting Michaelis-Menten Models](compare_gpp_models.html) (Clay Ford, 2025-01-15)      
How to compare two fitted curves using an interaction in a `nlme::gnls()` model.

- [Understanding the {ggeffects} predict_response() margin argument](ggeffects_margin_argument.html) (Clay Ford, 2025-01-10)    
Elaborating on the {ggeffects} vignette, [Difference Between Marginalization Methods: The margin Argument](https://strengejacke.github.io/ggeffects/articles/technical_differencepredictemmeans.html).

- [Intro to Mixed-Effect Modeling](intro_mixed_effect_modeling.html) (Clay Ford, 2024-12-18)     
Introduces mixed-effect modeling using simulated data and compares the results to wrong and older methods. 


- [Paired t-tests as mixed-effect model](paired_t_test_as_model.html) (Clay Ford, 2024-11-22)     
How to run many paired t-tests as a single mixed-effect model. Uses simulated data. 

- [tidyLPA notes](tidyLPA.html) (Clay Ford and Lauren Brideau, 2024-11-01)    
Notes on using the {tidyLPA} package and how it relates to the {mclust} package.


- [Mixed-Effect Modeling for ANOVA](mixed-effect_ANOVA.html) (Clay Ford, 2024-10-08)     
Demo of implementing ANOVA analysis for multilevel data. 

- [Using polycor::hetcor](using_polycor_hetcor.html) (Clay Ford, 2024-09-27)      
Demonstration of using the `hetcor()` function in the {polycor} package using simulated data.


- [Polyserial and Polychoric Correlation](polychoric_and_polyserial_correlations.html) (Clay Ford, 2024-09-24)      
An intro to polyserial and polychoric correlation using the {polycor} package. 


- [Post-hoc Comparisons with non-linear models](non_linear_mlm_with_comparisons.html) (Clay Ford, 2024-07-15)      
Simple demo of using `emmeans()` on a non-linear predictor.

- [Demo of Term plots](term_plots.html) (Clay Ford, 2024-06-25)     
Demonstration of using term plots to detect departures from linearity for coefficients. Shows the base R `termplot()` and `car::crPlots()` functions.


- [Assessing residuals with lineup lots](assessing_residuals.html) (Clay Ford, 2024-04-05)      
Using lineup plots to better interpret a QQ plot of model residuals. 

- [Compact Letter Displays](cld.html) (Clay Ford, 2024-03-24)    
How to create and interpret Compact Letter Displays, though [some people don't like them](https://stats.stackexchange.com/questions/275832/interpreting-compact-letter-displays-and-tukey-multiple-comparisons-from-glmm#comment829280_275832).

- [Complex reshaping example](complex_reshaping_example.html) (Clay Ford, 2024-02-15)      
The data set in question had six different sets of variables that needed to be reshaped into “long” format. Each set was collected over five waves. This shows how to do the reshaping using `pivot_longer()`.

- [Multivariate Paired Hotelling T Square Test](Multivariate_Paired_T_Test.html) (Clay Ford, 2024-02-27)      
How to implement a Multivariate Paired Hotelling T Square Test in R and SPSS.

- [Forced One-way ANOVA](forced_oneway_anova.html) (Clay Ford, 2023-12-01)    
Convert a two-way ANOVA into a one-way ANOVA.

- [Multilevel Quantile Regression](multilevel_quantile_regression.html) (Clay Ford, 2023-10-23)      
Example of Multilevel Quantile Regression using {lqmm} and simulated data. 


- [Data wrangling nc4 files](dw_nc4_files.html) (Clay Ford, 2023-10-18)     
Example of extracting values from nc4 object (netCDF) and converting to data frame.


- [Recoding example](recoding_example.html) (Clay Ford, 2023-10-06)       
Recoding example using a lookup table.

- [Multi-level model example using simulated data](example_analysis.html) (Clay Ford, 2023-10-03)    
Example of multi-level model written for someone who was brand new to R. Includes demo of {emmeans} and {ggeffects}.

- [Multilevel model example with 3 nested levels](multilevel_model_example.html) (Clay Ford, 2023-09-15)     
Example of a multilevel model with 3 levels of nested groups. Uses simulated data.


- [Data wrangling consultation](consultation_summary_2023-08-28.html) (Clay Ford, 2023-08-28)     
Data wrangling tasks: (1) drop any groups with less than 10 rows, (2) drop rows with runs of zeroes greater than or equal to 5.

- [Various t-test alternatives](statistical_analysis_approaches.html) (Clay Ford, 2023-02-21)      
Shows alternatives to t-tests, including log-transformed t-tests, Wilcoxon, permutation tests, and bootstrap. 


- [Split violin plots](split_violin_plots.html) (Clay Ford, 2022-10-18)     
Demo of how to create split violin plots using `introdataviz::geom_split_violin()`

- [The stats::filter() function](stats_filter_function.html) (Clay Ford, 2022-10-12)      
How to use the the base R `filter()` function to calculate moving averages.

- [Logistic regression interactions](logistic_regression_interactions.html) (Clay Ford, 2022-09-19)      
How to interpret and visualize 2-level categorical variable interactions in a logistic regression model.

- [Nested Factorial Experiment](nested_anova.html) (Clay Ford, 2022-09-19)     
Example of a Nested Factorial Experiment from _Statistical Models in S_.

- [How to adjust p-values using R](adjusted_pvalues_in_R.html) (Clay Ford, 2022-09-13)      
Quick demo of how to use Holm method to adjust p-values.


- [Three approaches to logistic regression in R](three_approaches_to_logistic_regression_in_R.html) (Clay Ford, 2022-07-18)    
Demo of three ways to fit a logistic regression model in R. 

- [Comparing a mediation analysis and with a t-test](mediation_analysis_ttest.html) (Clay Ford, 2022-05-25)       
The difference in means from a t-test is the “Total Effect” in mediation analysis.


- [Mediation Analysis with Multiple Imputation](MA_with_MI.html) (Clay Ford, 2022-04-25)      
An attempt at mediation analysis with multiply imputed data using the {mice} and {mediation} packages. 

- [Explaining large confidence intervals](large_CIs.html) (Clay Ford, 2022-04-05)      
Student wondered why confidence intervals on marginal means were so large. Due to small estimated degrees of freedom. 


- [Nomogram demo](nomogram_demo.html) (Clay Ford, 2022-03-31)     
This demonstration is a modification of the example available on the `nomogram()` help page from the {rms} package. It demonstrates a nomogram for a logistic regression model using simulated data.

- [mixed-effect proportional odds mode](simulate_analysis.html) (Clay Ford, 2022-02-25)       
An example of a mixed-effect proportional odds mode using simulated data and the `clmm()` function from the {ordinal} package.

- [Robustness of t-test](robustness_of_t-test.html) (Clay Ford, 2022-01-07)    
Simulation demonstrating robustness of t-test to non-normal data.


- [ANCOVA example](ancova_example.html) (Clay Ford, 2022-01-07)     
Quick demo of using Analysis of Covariance to compare trends over time.

- [Identifying peaks in a line plot](finding_peaks.html) (Clay Ford, 2021-06-14)     
One possible method of identifying peaks in a line plot using the `findpeaks()` function in the {pracma} package.


- [Bootstrapped diff in means](bootstrap_example.html) (Clay Ford, 2021-12-11)      
Example of implementing a bootstrapped difference in means as an alternative to a t-test using the {boot} package in R.


- [Multilevel Model power analysis](power_analysis_simulation.html) (Clay Ford, 2021-10-04)     
Power analysis for a multilevel model with a Likert outcome ranging from 1-5 and a simple binary treatment variable. Presents two approaches: (1) manual simulation, and (2) the {simr} package.


- [logistic regression for a 2x2 table](logistic_regression_example.html) (Clay Ford, 2021-06-09)      
Example of using logistic regression to get odds ratio, confidence interval on OR, and the p-value testing null if OR is 1.


- [Plotting Derivatives](plot_derivatives.html) (Clay Ford, 2021-05-17)      
Calculating and plotting first and second derivatives.

- [Comparing Trends with ANCOVA](comparing_slopes.html) (Clay Ford, 2021-04-22)    
Comparing slopes via ANCOVA and {emmeans} using simulated data.

- [Demo of Generalized Linear Mixed Model](glmm.html) (Clay Ford, 2021-02-12)    
A demonstration of binomial GLMM using simulated data.

- [CIs for Cramer's V](cramers_v.html) (Clay Ford, 2021-01-20)    
Demo of calculating CIs for Cramer's V for a small sample.

- [Normality is for Residuals](normality_is_for_residuals.html) (Clay Ford, 2020-11-02)     
The normality assumption in linear modeling (multiple regression) is on the residuals, not the dependent or independent variables.

- [Stepwise Model Selection performing poorly](stepwise_simulation.html) (Clay Ford, 2020-09-01)     
Demo of stepwise model selection performing poorly in the presence of collinearity. [Stepwise selection should be avoided anyway](https://discourse.datamethods.org/t/reference-collection-to-push-back-against-common-statistical-myths/1787#p-4596-stepwise-variable-selection-dont-do-it-7).